### ISSUE TITLE
Provide one prebuilt java file pls

### ISSUE THREAD

**Issue by AFrenchCroissant** [Nixuge/BlockSumoPlugin#5]
hello, i have no clue how to build this on the underpowered server i want to run this on (for fun, and maybe to play with friend)
It would be greatly apreciated if you could provide a prebuild jar file please (or redirect me on how to build it on terminal linux)
thank you !!!

**Comment by Nixuge** [comment]
Made a quick release

https://github.com/Nixuge/BlockSumoPlugin/releases/tag/1.0.0

Note that I don't remember the state this thing is in, iirc everything is implemented (at least in basic form) but you check it out for yourself.

Also note that there's no lobby & it's made to run on a server alone, not a subworld or anything
